### ISSUE TITLE
Each run of meetup api sync doubles participants

### ISSUE THREAD

**Issue by panterch** [rubyonrails-ch/ror_ch#15]
Loading production environment (Rails 4.2.1)
irb(main):001:0> Participant.count
   (12.4ms)  SELECT COUNT(*) FROM "participants"
=> 418

**Comment by panterch** [comment]
This was fixed by @skmp in https://github.com/panterch/ror_ch/commit/43063974b6a78cb66a676f5f8bc3986f52b46fba 

Although not completely mandatory, you should run a 

```bundle exec rake db:reset && bundle exec rails runner MeetupJob.new.perform```

**Comment by masone** [comment]
Introduced with the rewrite to pgsql. Thanks for the fix.
