### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by koffeinfrei** [rubyonrails-ch/ror_ch#17]
Here are the first few logo drafts and ideas. Please vote or add new proposals.

A)
![logo_christian](https://cloud.githubusercontent.com/assets/176582/7993509/304e2be6-0b0f-11e5-8967-b55b402f4162.png)

B)
![logo_klassenlager](https://cloud.githubusercontent.com/assets/176582/7993536/6fcc0518-0b0f-11e5-9675-36b8a868be0f.png)

C1)
![ror-logo-kuh-kopf](https://cloud.githubusercontent.com/assets/176582/7993501/27e16cf2-0b0f-11e5-83f1-c0978fdd50d8.png)

C2)
![ror-logo-kuh-schwanz](https://cloud.githubusercontent.com/assets/176582/7993502/281b8aa4-0b0f-11e5-937b-5352bc3cd809.png)

**Comment by m1nuted** [comment]
I'd say option A for the "Official" logo and the two cows for the stickers/badges if there will be!

**Comment by domicode** [comment]
B

**Comment by panterch** [comment]
I like B better but could live with A

**Comment by huerlisi** [comment]
I'd vote for B, and am with @m1nuted regarding the cow stickers.

**Comment by robinbortlik** [comment]
I like A as a logo and D is must have sticker :)

**Comment by tomaswitek** [comment]
B

**Comment by johndel** [comment]
A

**Comment by geku** [comment]
I like B but think it is a bit unimaginative as it is just the Ruby logo and does not communicate the Rails part, therefore I like A better because it unions Rails and Switzerland.

**Comment by yannick** [comment]
A
the idea of b is pretty funky but i think it could be slightly developed further

**Comment by reactormonk** [comment]
A, maybe B if the cross were bigger.

**Comment by panterch** [comment]
Further work on the B) Variant:

B1)

![unnamed](https://cloud.githubusercontent.com/assets/15120/8019681/6e6f6b6a-0c63-11e5-8781-6e4a8cc995a1.png)

B2)

![unnamed-2](https://cloud.githubusercontent.com/assets/15120/8019684/83412d08-0c63-11e5-8146-62fcbf787939.png)

Thanks to Micheal!

**Comment by koffeinfrei** [comment]
i like the simplicity of b. i think b2 is better with the bigger cross. i believe the cross should be white though in order to be associated with switzerland.

**Comment by domicode** [comment]
![ror_ch logo](https://cloud.githubusercontent.com/assets/7032563/8024601/32e68e76-0d39-11e5-8f1b-7cc11e65dd13.jpg)

**Comment by masone** [comment]
Thanks for working on more variants and new suggestions! Let's keep in mind that it's more about rails than ruby. Maybe we can suggest B to http://ruvetia.org ;)

**Comment by masone** [comment]
![ror_ch-ruby](https://cloud.githubusercontent.com/assets/2797/8024809/7be2f4be-0d40-11e5-841d-26cc056e5284.png)

The original shape of A is the one of the [swiss federation](https://www.admin.ch/gov/de/_jcr_content/logo/image.imagespooler.png/1422517526791/Logo%20Schweizerische%20Eidgenossenschaft.png). Seeing so many rubies here, I thought I'd give it a try too.

**Comment by schiratzki** [comment]
Original B

**Comment by lukaseppler** [comment]
B. Maybe the cross could go to the top? Like a sparkle?

**Comment by somebox** [comment]
@panterch I think B1 is very strong and simple. :+1: I would suggest a red or white cross and a bit more space between the elements.

**Comment by reactormonk** [comment]
@domicode Could you make the first one without the rails attached?

**Comment by geku** [comment]
I still like A (or A in a Ruby shape) because of a better association to Rails compared to B versions.

Another play just with the Ruby (also not my favorite ...):
![rails](https://cloud.githubusercontent.com/assets/4066/8092174/5fdf2fd8-0fb8-11e5-9430-a2706cc550ed.png)

**Comment by panterch** [comment]
Let's proceed it like this:

     number of commits on ror_ch repo == your votes in this thread

scnr

**Comment by masone** [comment]
Thanks for the votes, inputs and new ideas. Unfortunately this discussion did not yield clear results. I'd say let's keep on discussing this face to face and find a way how to proceed.
