### ISSUE TITLE
Time offset

### ISSUE THREAD

**Issue by masone** [rubyonrails-ch/ror_ch#6]
Events show 16:30, but it should be 18:30. Propably displaying utc instead of local timezone.

![screen shot 2015-05-27 at 15 28 16](https://cloud.githubusercontent.com/assets/2797/7837046/0672c9ac-0485-11e5-8282-593e368ee610.png)

**Comment by panterch** [comment]
This is fixed with https://github.com/panterch/ror_ch/commit/007c20d5c51ad7b89e4db3cb53f5989803cb9a5c
