### ISSUE TITLE
Switch to a different ActiveJob backend

### ISSUE THREAD

**Issue by masone** [rubyonrails-ch/ror_ch#9]
currently using sucker_punch / fist_of_fury which is pretty cool on heroku since it runs in the web process. especially fist_of_fury feels hacky. if we move away from heroku in #8, let's switch to another worker system (eg. sidekiq or goworker).

**Comment by panterch** [comment]
Actually for the use case something like whenever would be more suitable?
https://github.com/javan/whenever

**Comment by panterch** [comment]
Fixed in #14

**Comment by masone** [comment]
Whenever is good for scheduling tasks, but I would not use it as a replacement for proper background processing. Also there will be a couple of uses where we need background jobs that are not scheduled. I'd really stick to ActiveJob.

**Comment by masone** [comment]
50b2aad1f0fb7345a620d69d39b29add922d9e7c migrates to sidekiq, a lot of peoples favorite background processing solution
